apiVersion: v1
kind: ServiceAccount
metadata:
  name: aggregator-cleaner
  namespace: aggregator-ops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aggregator-cleaner-role
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aggregator-cleaner-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aggregator-cleaner-role
subjects:
- kind: ServiceAccount
  name: aggregator-cleaner
  namespace: aggregator-ops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-cleaner
  namespace: aggregator-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator-cleaner
  template:
    metadata:
      labels:
        app: aggregator-cleaner
    spec:
      serviceAccountName: aggregator-cleaner
      containers:
      - name: aggregator-cleaner
        image: aggregator-cleaner
        imagePullPolicy: Never
        args: ["--ns=aggregator-app"]
