# ========================
# 1 Service Account
# ========================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aggregator-sa
  namespace: aggregator-app
---
# ========================
# 2 ClusterRole: namespace management + Traefik middleware
# ========================
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aggregator-namespace-manager
rules:
  # Built-in resources
  - apiGroups: [""]
    resources: ["namespaces", "pods", "services", "configmaps", "serviceaccounts"]
    verbs: ["get", "list", "create", "delete", "update", "patch", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "delete", "update", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "create", "delete", "watch"]
  - apiGroups: [ "discovery.k8s.io" ]
    resources: [ "endpointslices" ]
    verbs: [ "get", "list", "watch" ]
  # Traefik CRDs
  - apiGroups: ["traefik.io"]
    resources: ["middlewares", "ingressroutes"]
    verbs: ["get", "list", "create", "update", "delete", "watch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "create", "update", "delete", "watch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles"]
    resourceNames: ["admin"]
    verbs: ["bind"]
  # Istio CRDs
  - apiGroups: ["networking.istio.io"]
    resources: ["serviceentries", "virtualservices", "destinationrules", "gateways", "envoyfilters"]
    verbs: ["get", "list", "create", "update", "delete", "watch"]
---
# ========================
# 3 ClusterRoleBinding: bind SA to role
# ========================
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aggregator-namespace-manager-binding
subjects:
  - kind: ServiceAccount
    name: aggregator-sa
    namespace: aggregator-app
roleRef:
  kind: ClusterRole
  name: aggregator-namespace-manager
  apiGroup: rbac.authorization.k8s.io
---
# ========================
# 4 Deployment
# ========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-server
  namespace: aggregator-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator-server
  template:
    metadata:
      labels:
        app: aggregator-server
    spec:
      serviceAccountName: aggregator-sa
      containers:
        - name: aggregator-server
          image: aggregator-server
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: aggregator-config
                  key: log_level
            - name: DISABLE_AUTH
              valueFrom:
                configMapKeyRef:
                  name: aggregator-config
                  key: disable_auth
            - name: CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: aggregator-config
                  key: client_id
            - name: CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: aggregator-config
                  key: client_secret
            - name: ALLOWED_REGISTRATION_TYPES
              valueFrom:
                configMapKeyRef:
                  name: aggregator-config
                  key: allowed_registration_types
            - name: PROVISION_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: aggregator-config
                  key: provision_client_id
            - name: PROVISION_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: aggregator-config
                  key: provision_client_secret
            - name: PROVISION_WEBID
              valueFrom:
                configMapKeyRef:
                  name: aggregator-config
                  key: provision_webid
            - name: PROVISION_AUTHORIZATION_SERVER
              valueFrom:
                configMapKeyRef:
                  name: aggregator-config
                  key: provision_authorization_server
            - name: AGGREGATOR_EXTERNAL_HOST
              value: "aggregator.local"
---
# ========================
# 5 Service: expose aggregator
# ========================
apiVersion: v1
kind: Service
metadata:
  name: aggregator-server-svc
  namespace: aggregator-app
spec:
  type: ClusterIP
  selector:
    app: aggregator-server
  ports:
    - port: 5000
      targetPort: 5000
---
# =======================
# 6 Ingress
# ========================
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: aggregator-server-ingressroute
  namespace: aggregator-app
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`aggregator.local`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: aggregator-server-svc
          port: 5000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: aggregator-server-registration-ingressroute
  namespace: aggregator-app
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`aggregator.local`) && PathPrefix(`/registration`)
      kind: Rule
      services:
        - name: aggregator-server-svc
          port: 5000
---
