# ------------------------
# ðŸ”¹ ConfigMap
# ------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregator-config
  namespace: aggregator-app
data:
  log_level: "info"                         # Set log level (debug, info, warn, error)
