apiVersion: v1
kind: Pod
metadata:
  name: ingress-uma
  namespace: aggregator-app
  labels:
    app: ingress-uma
spec:
  containers:
    - name: ingress-uma
      image: ingress-uma
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
      env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: aggregator-config
              key: log_level
        - name: EXTERNAL_HOST
          value: "aggregator.local"
      volumeMounts:
        - name: uma-key-volume
          mountPath: /keys
          readOnly: true
  volumes:
    - name: uma-key-volume
      secret:
        secretName: ingress-uma-key
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-uma
  namespace: aggregator-app
spec:
  type: ClusterIP
  selector:
    app: ingress-uma
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-uma-ingress
  namespace: aggregator-app
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: aggregator-app-strip-uma-prefix@kubernetescrd
spec:
  ingressClassName: aggregator-traefik
  rules:
    - host: "aggregator.local"
      http:
        paths:
          - pathType: Prefix
            path: /uma
            backend:
              service:
                name: ingress-uma
                port:
                  number: 80
---
