apiVersion: v1
kind: Secret
metadata:
  name: uma-proxy-key-pair
  namespace: uma-proxy-ns
type: Opaque
stringData:
  # These will be populated dynamically by the Makefile
  uma-proxy.crt: PLACEHOLDER_CERT
  uma-proxy.key: PLACEHOLDER_KEY
