apiVersion: v1
kind: Namespace
metadata:
  name: aggregator-ns
---
apiVersion: v1
kind: Pod
metadata:
  name: ingress-uma
  namespace: aggregator-ns
  labels:
    app: ingress-uma
spec:
  containers:
    - name: ingress-uma
      image: ingress-uma
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
      env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: aggregator-config
              key: log_level
      volumeMounts:
        - name: uma-key-volume
          mountPath: /keys
          readOnly: true
  volumes:
    - name: uma-key-volume
      secret:
        secretName: ingress-uma-key
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-uma
  namespace: aggregator-ns
spec:
  type: ClusterIP
  selector:
    app: ingress-uma
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080